# Generated by Django 3.0 on 2019-12-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Articles',
        ),
    ]
